### ISSUE TITLE
Skip xx Zeit pro Podcast

### ISSUE THREAD

**Issue by zeitiger** [JeanetteMueller/Podcat2#17]
Intro und Werbung am Anfang überspringen

**Comment by JeanetteMueller** [comment]
Pro Podcast? Bitte genauer erläutern.

**Comment by zeitiger** [comment]
Ich möchte bei Podcast bspw. die erste Minute überspringen können um so die Werbung bzw. das Intro zu überspringen.

**Comment by JeanetteMueller** [comment]
Und wie/wo soll das möglich sein? Ich kann die App nicht mit zu vielen Buttons zukleistern. 
Wie wird das in anderen Apps gelöst?

**Comment by zeitiger** [comment]
In Pocket Cast ist es damit gelöst das man es in den Podcast/Subscription Settings einstellt. 
https://www.dropbox.com/s/b1eq8mtcbipccrt/Datei%2007.03.17%2C%2015%2018%2053.png?dl=0

**Comment by zeitiger** [comment]
Es darf auch gerne im hintersten Eck der Einstellung des einzelnen Podcast sein, das stellt man in der Regel einmal ein und lebt damit

**Comment by JeanetteMueller** [comment]
ah, ein default der immer greift und nicht vom user per "werbung überspringen"-button ausgelöst wird. 
interessant...

**Comment by zeitiger** [comment]
https://www.dropbox.com/s/9wjyw4xc8jqufyi/Datei%2007.03.17%2C%2015%2033%2051.png?dl=0 in dieser UI wäre es wohl am besten aufgehoben

**Comment by JeanetteMueller** [comment]
Ist eingebaut und getestet. Zum Wochenende übergebe ich das dann an den AppStore
