### ISSUE TITLE
Small-Theme

### ISSUE THREAD

**Issue by zeitiger** [JeanetteMueller/Podcat2#19]
Icon und Abstände verkleinern um mehr zu sehen

**Comment by JeanetteMueller** [comment]
Ein eigenes Theme für ein "engeres" layout? Eine bessere UI Optimierung für kleinere Screens kann ich mir schon vorstellen aber ein separates Theme zu managen wäre zuviel des Guten.

**Comment by JeanetteMueller** [comment]
Das Podcast-Gitter "Abonniert" erkennt nun Displaygrößen und variiert entsprechend den Abstand zwischen den Coverbildern

**Comment by JeanetteMueller** [comment]
Episodenzeilen werden für kleines Screens auch weniger hoch dargestellt. Höhe regulär 90, wird auf 80 und auf dem SE auf 70 reduziert

**Comment by JeanetteMueller** [comment]
![screenshot 2017-02-24 23 02 37](https://cloud.githubusercontent.com/assets/22024/23322688/62e33a16-fae5-11e6-8287-565fd319489c.png)

**Comment by JeanetteMueller** [comment]
![screenshot 2017-02-24 23 03 20](https://cloud.githubusercontent.com/assets/22024/23322703/73651ce2-fae5-11e6-8f4f-3a33fe2977b2.png)

**Comment by zeitiger** [comment]
Die Abstände im Einstellungsmenü könnten noch kleiner sein.
Die obere Menüleiste (Ungespielt, Stern, Kamera, Download) sollte so groß sein wie die Menüleiste bei einem Podcast (Ungespielt, Favoriten, Videos, Suche)
BTW: Warum einmal Icons und dann wiederum nur Text?
Ansonsten sieht es schon viel besser auf dem iPhone SE aus. Danke :-D

**Comment by JeanetteMueller** [comment]
Ungespielt, Stern, Kamera und Download sind Gruppen, keine Filter. 
Ich könnte diese Gruppen auch normal jeweils als eine Zeile darstellen wie die von User angelegten Gruppen. Dachte mir aber mal will man lieber die Systemgruppen nutzen, mal lieber die eigenen. Damit man nicht so viel scroll muss hab ich die system eigenen Gruppen eben zusammengefasst.

**Comment by JeanetteMueller** [comment]
Settings Zeilenhöhe von 80 auf die dynamische Höhe geändert, auf dem SE bleibt dann eine Höhe von 48px übrig
