### ISSUE TITLE
UI Kontextmenü abbrechen

### ISSUE THREAD

**Issue by zeitiger** [JeanetteMueller/Podcat2#20]
Es sollte möglich sein das Menü zu verlassen wenn man außerhalb tappt

**Comment by JeanetteMueller** [comment]
Wenn damit die Overlay-Menüs gemeint sind dann hab ich hier wenig Einfluss. Diese sind 100% Systemfunktionen.

**Comment by JeanetteMueller** [comment]
Aber es gibt dennoch einen Weg das Ergebnis zu bekommen. Done
