### ISSUE TITLE
Kapitelmarker in Timeline

### ISSUE THREAD

**Issue by thomasvoni** [JeanetteMueller/Podcat2#21]
Im Player (Timeline) Kapitelmarken anzeigen, damit auf ein Blick erkennt werden kann wo die Kapitel sind.

**Comment by JeanetteMueller** [comment]
versteh ich nicht recht. Timeline? 
Sollen die Kapitel (aktuelles, letztes und nächstes) im großen Player angezeigt werden statt oder zusätzlich zu dem großen "Kapitelmarken" Button?

**Comment by thomasvoni** [comment]
![podcat-kapitel](https://cloud.githubusercontent.com/assets/25966347/23254943/1508acda-f9ba-11e6-9af9-b8a6422411e2.png)
Bin kein Designer aber so könnte ich mir das vorstellen... :-)

**Comment by JeanetteMueller** [comment]
oha, das ist gar keine schlechte Idee :)

**Comment by JeanetteMueller** [comment]
![2017-02-25 00 06 40](https://cloud.githubusercontent.com/assets/22024/23324506/7601a25a-faee-11e6-9a43-7ebedd3de583.png)
