### ISSUE TITLE
Später-Lese-Dienst einbinden

### ISSUE THREAD

**Issue by thomasvoni** [JeanetteMueller/Podcat2#22]
z.B. Pocket, damit ein Kapitel möglichst einfach (z.B. während Autofahrt) markiert werden kann um später die Shownotes nachzulesen.

**Comment by JeanetteMueller** [comment]
Deep-Links von aktueller Wiedergabeposition erzeugen und verwenden fehlen tatsächlich noch. Ich übertrage das mal in ein neues, für mich verständlicheres Ticket

**Comment by JeanetteMueller** [comment]
Integration von anderen Systemen unter "Accounts" in den Settings eingebaut.

**Comment by JeanetteMueller** [comment]
Episode Sharing per Pocket eingebaut
