### ISSUE TITLE
Während des Importieren eines OPML blockiert die App

### ISSUE THREAD

**Issue by Gawetaner** [JeanetteMueller/Podcat2#24]
**Bug Report**
Während des Importieren eines OPML blockiert die App.

**Submitter**
Dennis Johannisson
mail@gawetaner.de

**Date Seen**
23.02.2017

**Versions**
OS: iOS 10.2.1
Device: iPhone 7
App: Podcat 2.1.1

**Bug Description**
Während des Import einer OPML Datei die von der App Downcast erstellt wurde blockiert das Interface der App für mehrere Sekunden. Bei meinem Versuch knapp eine Minute.

Im Anhang befindet sich die verwendete OPML Datei. Ich musste die Dateiendung anpassen damit GitHub den Upload erlaubt.

**Severity**
Minor

**Steps to Reproduce**
1. Podcat aus dem Appstore installieren
2. Podat App starten
3. Downcast App öffnen und OPML über den "Öffnen in" Dialog in Podcat Importieren
4. Alle Podcast auswählen und Importieren. 

**Actual Behavior**
App blockiert für mehrere Sekunden.

**Expected Behavior**
App lässt sich auch während des Imports bedienen oder zeigt einen Overlay der auf den Importprozess hinweist.

[Downcast.txt](https://github.com/JeanetteMueller/Podcat2/files/796032/Downcast.txt)

**Comment by JeanetteMueller** [comment]
ist bekannt, generell das aktualisieren von allen feeds unter "Abonniert" hat das selbe Problem und wird bald möglichst gelöst
