### ISSUE TITLE
App crasht bei jedem Start sofort (v2.1.2)

### ISSUE THREAD

**Issue by noinfo** [JeanetteMueller/Podcat2#30]
Seit dem Update 2.1.2 lässt sich PodCat nicht mehr öffnen. Nach dem Startscreen geht es direkt zurück zum Homescreen. 

Hardware: iPhone 6 Plus
Software: iOS 10.2

**Comment by JeanetteMueller** [comment]
Problem ist bekannt und 2.1.3 wartet auf Apples Freigabe um das Problem zu lösen

**Comment by noinfo** [comment]
Ich warte gespannt! Der Weg zur Arbeit ohne Podcat ist merklich anstrengender. :-)
