### ISSUE TITLE
übergeordnete Wiedergeschwindigkeit hinzufügen

### ISSUE THREAD

**Issue by iknorry** [JeanetteMueller/Podcat2#39]
In den Einstellungen - Wiedergabe - Wiedergabegeschwindigkeit "eine übergeordnete Geschwindigkeit (für alle Podcast) hinzufügen"

**Comment by iknorry** [comment]
Natürlich Wieder"gabe"geschwindigkeit im Titel gemeint

**Comment by JeanetteMueller** [comment]
eingebaut. also man kann nun alle werte für alle podcasts auf einmal ändern

**Comment by iknorry** [comment]
Super! Danke!

Freundlicher Gruß
Dr. Jochen Pütter
